<a href="https://colab.research.google.com/github/sus4157d/almabetter/blob/main/Important_ML_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import Libraries
import numpy as np
import pandas as pd
from numpy import math

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import GridSearchCV
from scipy.stats import zscore
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge

import warnings
warnings.filterwarnings('ignore')
from datetime import date
from datetime import datetime

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/bike_sharing/SeoulBikeData.csv",encoding = "ISO-8859-1")

In [ ]:
from datetime import date
from datetime import datetime

In [ ]:
df_cardekho.drop_duplicates(keep='first', inplace=True)

In [ ]:
# converting date to week no.
df['Date']=pd.to_datetime(df['Date'])
df['Week_number'] = df['Date'].dt.isocalendar().week
df['date_month']=df['Date'].dt.isocalendar.date
df['day_week']=df['Date'].dt.weekday

In [ ]:
len(df[df.duplicated()])

In [ ]:
dfn['company_cat']=dfn['mean_price'].apply(lambda x: 0 if x < 3.136715e+05 else (1 if x<5.044551e+05 else 2))

In [ ]:
dfn=dfn.merge(dftemp,on="company",how="left")

In [ ]:
dfn.drop(index=index_d,inplace=True)

In [ ]:
plt.figure(figsize=(7,4))
sns.distplot(dfn["selling_price"])

In [ ]:
dfn.drop_duplicates(inplace=True)

In [ ]:
from sklearn.preprocessing import FunctionTransformer
transformer = FunctionTransformer(np.log1p)
transformer.transform(X)

Below are the some type of method or way to deal above type of problem.

square-root for moderate skew: sqrt(x) for positively skewed data, sqrt(max(x+1) - x) for negatively skewed data

log for greater skew: log10(x) for positively skewed data, log10(max(x+1) - x) for negatively skewed data

inverse for severe skew: 1/x for positively skewed data 1/(max(x+1) - x) for negatively skewed data

Linearity and heteroscedasticity: First try log transformation in a situation where the dependent variable starts to increase more rapidly with increasing independent variable values If your data does the opposite – dependent variable values decrease more rapidly with increasing independent variable values – you can first consider a square transformation.

In [ ]:
for col in numeric_features:
    fig = plt.figure(figsize=(9, 6))
    ax = fig.gca()
    feature = df_cardekho[col]
    feature.hist(bins=50, ax = ax)
    ax.axvline(feature.mean(), color='magenta', linestyle='dashed', linewidth=2)
    ax.axvline(feature.median(), color='cyan', linestyle='dashed', linewidth=2)
    ax.set_title(col)
plt.show()

In [ ]:
plt.figure(figsize=(8,5))
sns.regplot(x='Car Age',y='selling_price',data=df_cardekho,color='red')

In [ ]:
def calc_vif(X):

   # Calculating VIF
   vif = pd.DataFrame()
   vif["variables"] = X.columns
   vif["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

   return(vif)

In [ ]:
calc_vif(df_cardekho[[i for i in df_cardekho.describe().columns if i not in ['year','selling_price']]])

In [ ]:
feature.extend(['Funct_day_No', 'Funct_day_Yes', 'Holiday_Holiday',
       'Holiday_No Holiday'])

In [ ]:
dfc=pd.get_dummies(dfc,columns=["Funct_day","Holiday"],prefix=["Funct_day","Holiday"])

In [ ]:
encoder_num={'Seasons':{'Autumn':0,'Winter':1,'Spring':2,'Summer':3}}
dfc=dfc.replace(encoder_num)

In [ ]:
for col in cat_f:
  fig=plt.figure(figsize=(8,5))
  ax=fig.gca()
  df.boxplot(column="Rent_bike_count",by=col,ax=ax)
  ax.set_title("label by "+col)
  ax.set_title("Bike_count")
plt.show()

In [ ]:
for col in cat_f:
  counts=df[col].value_counts().sort_index()
  fig=plt.figure(figsize=(8,5))
  ax=fig.gca()
  counts.plot.bar(ax=ax,color='red')
  plt.title(col + " counts ")
  plt.xlabel(col)
  plt.ylabel("freq")
plt.show()

In [ ]:
df=df[df["Rent_bike_count"]>0]

Here are three common evaluation metrics for regression problems:

Mean Absolute Error (MAE) is the mean of the absolute value of the errors:

1n∑i=1n|yi−y^i|

Mean Squared Error (MSE) is the mean of the squared errors:

1n∑i=1n(yi−y^i)2

Root Mean Squared Error (RMSE) bold text is the square root of the mean of the squared errors:

1n∑i=√1n(yi−y^i)2

Comparing these metrics:

MAE is the easiest to understand, because it's the average error.
MSE is more popular than MAE, because MSE "punishes" larger errors, which tends to be useful in the real world.
RMSE is even more popular than MSE, because RMSE is interpretable in the "y" units.
All of these are loss functions, because we want to minimize them.

In [ ]:
# Visualizing evaluation Metric Score chart
def eval_metric(y_test,y_pred):
  MSE  = mean_squared_error((y_test), (y_pred))
  print("MSE :" , MSE)

  MAE=mean_absolute_error((y_test), (y_pred))
  print("MAE :" ,MAE)

  RMSE = np.sqrt(MSE)
  print("RMSE :" ,RMSE)

  r2 = r2_score((y_test), (y_pred))
  print("R2 :" ,r2)
  print("Adjusted R2 : ",1-(1-r2_score((y_test), (y_pred)))*((X_test.shape[0]-1)/(X_test.shape[0]-X_test.shape[1]-1)))

In [ ]:
#feature.extend(['Funct_day_No', 'Funct_day_Yes', 'Holiday_Holiday',
 #      'Holiday_No Holiday','Seasons_Autumn',	'Seasons_Spring',	'Seasons_Summer',	'Seasons_Winter'])

In [ ]:
#dfc=pd.get_dummies(dfc,columns=["Funct_day","Holiday","Seasons"],prefix=["Funct_day","Holiday","Seasons"])

In [ ]:
[[3745  388]
 [ 819  682]]

accuracy - How accurate i am . i predicated churn and it actually churned plus i predicated not churn and it acutally didnt churn.
divided by total no of all the cases.3745+682/3745+388+819+682


precision=how precise i am in prediciton. i predicted churn and actually churned divided by sum of predicted churn and actually churn plus predicted churn and didnot churn 682/682+388

recall-how much i am able to recall. i predicted churn and actuall churned divided by sum of acutally churned (predicted churn and actually churn plus prdicated not churne and actuall churn 682/682+819

In [ ]:
insurance_df = insurance_df.dropna(thresh=insurance_df.shape[0]*0.4,axis=1)
#droping column with more than 40 per of na value

In [ ]:
#impoptant lybrary
import pandas as pd
import numpy as np
import re
from datetime import datetime
#machine learning
import xgboost as xgb
from xgboost import XGBClassifier
#for hyperparameter tunning and cross velidation
from sklearn.model_selection import TimeSeriesSplit
from sklearn.model_selection import RandomizedSearchCV , GridSearchCV
#lyb for evaluation of model
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score,log_loss
#lyb for understanding model perdiction
import shap
shap.initjs()
import glob


In [ ]:
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows', 200)

In [ ]:
dfa=dfn.dropna(subset = ['genres'])

In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer(sparse_output=True)

dfa = dfa.join(
            pd.DataFrame.sparse.from_spmatrix(
                mlb.fit_transform(dfa.pop('genres')),
                index=dfa.index,
                columns=mlb.classes_))

In [ ]:
pd.set_option('display.max_colwidth', -1)

In [ ]:
# Hyperparameter tuning

classifier = RandomForestClassifier() # For GBM, use GradientBoostingClassifier()
grid_values = {'n_estimators':[50, 80,  100], 'max_depth':[3, 5, 7]}
classifier = GridSearchCV(classifier, param_grid = grid_values, scoring = 'roc_auc', cv=5)

# Fit the object to train dataset
classifier.fit(X_train, Y_train)

In [ ]:
# Number of trees
n_estimators = [50,80,100]

# Maximum depth of trees
max_depth = [4,6,8]

# Minimum number of samples required to split a node
min_samples_split = [50,100,150]

# Minimum number of samples required at each leaf node
min_samples_leaf = [40,50]

# HYperparameter Grid
param_dict = {'n_estimators' : n_estimators,
              'max_depth' : max_depth,
              'min_samples_split' : min_samples_split,
              'min_samples_leaf' : min_samples_leaf}# Create an instance of the RandomForestClassifier
rf_model = RandomForestClassifier()

# Grid search
rf_grid = GridSearchCV(estimator=rf_model,
                       param_grid = param_dict,
                       cv = 5, verbose=2, scoring='roc_auc')

rf_grid.fit(X_train,Y_train)
rf_grid.best_estimator_
rf_optimal_model = rf_grid.best_estimator_
# Making predictions on train and test data

train_class_preds = rf_optimal_model.predict(X_train)
test_class_preds = rf_optimal_model.predict(X_test)


# Get the probabilities on train and test
train_preds = rf_optimal_model.predict_proba(X_train)[:,1]
test_preds = rf_optimal_model.predict_proba(X_test)[:,1]
rf_optimal_model.feature_importances_
importances = rf_optimal_model.feature_importances_

importance_dict = {'Feature' : list(X_train.columns),
                   'Feature Importance' : importances}

importance_df = pd.DataFrame(importance_dict)
importance_df['Feature Importance'] = round(importance_df['Feature Importance'],2)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.metrics import auc

In [ ]:
lr = LogisticRegression()
rf = RandomForestClassifier()
xgb = XGBClassifier(objective= 'binary:logistic', nthread=4, seed=42)
param_dict_lr = {
    'C' : [1e-6,1e-5,1e-4,1e-3,1e-2,1e-1,1,10,100,1e-3,1e+4,1e+5,1e+6]
}

param_dict_rf = {
    'max_depth': [4, 6, 8],
    'min_samples_leaf': [40, 50],
    'min_samples_split': [50, 100, 150],
    'n_estimators': [50, 80, 100]
  }

param_dict_xgb = {
    'max_depth': range (2, 10, 1),
    'n_estimators': range(60, 220, 40),
    'learning_rate': [0.1, 0.05, 0.01, 0.005]
  }
  lr_grid = GridSearchCV(estimator=lr,
                       param_grid = param_dict_lr,
                       cv = 5, verbose=2, scoring='roc_auc')

lr_grid.fit(X_train,y_train)
print('Train ROC-AUC score : ', lr_grid.best_estimator_.score(X_train,y_train))
print('Test ROC-AUC score : ', lr_grid.best_estimator_.score(X_test,y_test))
lr_random = RandomizedSearchCV(estimator=lr,
                       param_distributions = param_dict_lr,
                       cv = 5, verbose=2, scoring='roc_auc')

lr_random.fit(X_train,y_train)
print('Train ROC-AUC score : ', lr_random.best_estimator_.score(X_train,y_train))
print('Test ROC-AUC score : ', lr_random.best_estimator_.score(X_test,y_test))
lr_bayes = BayesSearchCV(estimator=lr,
                       search_spaces = {'C' : Real(1e-6, 1e+6, prior='log-uniform') },
                       cv = 5, verbose=2, scoring='roc_auc', n_iter=32)

lr_bayes.fit(X_train,y_train)
lr_bayes.best_estimator_
rf_grid = GridSearchCV(estimator=rf,
                       param_grid = param_dict_rf,
                       cv = 5, verbose=2, scoring='roc_auc')

rf_grid.fit(X_train,y_train)
rf_grid.best_params_
rf_random = RandomizedSearchCV(estimator=rf,
                       param_distributions = param_dict_rf,
                       cv = 5, verbose=2, scoring='roc_auc')

rf_random.fit(X_train,y_train)
rf_random.best_params_
rf_bayes = BayesSearchCV(estimator=rf,
                       search_spaces = {
                          'max_depth': Integer(4,8),
                          'min_samples_leaf': Integer(10,100),
                          'min_samples_split': Integer(50,150),
                          'n_estimators': Integer(10,100)
                        },
                       cv = 5, verbose=2, scoring='roc_auc')

rf_bayes.fit(X_train,y_train)
rf_bayes.best_params_
rf_model = rf_bayes.best_estimator_
xgb_grid = GridSearchCV(estimator=xgb,
                       param_grid = param_dict_xgb,
                       cv = 5, verbose=2, scoring='roc_auc')

xgb_grid.fit(X_train,y_train)
xgb_grid.best_params_
xgb_random = RandomizedSearchCV(estimator=xgb,
                       param_distributions = param_dict_xgb,
                       cv = 5, verbose=2, scoring='roc_auc')

xgb_random.fit(X_train,y_train)
xgb_random.best_params_
xgb_bayes = BayesSearchCV(estimator=xgb,
                       search_spaces = {
                          'max_depth': Integer(2, 10),
                          'n_estimators': Integer(60, 220),
                          'learning_rate': Real(0.001, 0.1, prior='log-uniform')
                        },
                       cv = 5, verbose=2, scoring='roc_auc', n_jobs=10)

xgb_bayes.fit(X_train,y_train)
xgb_model = xgb_grid.best_estimator_

In [ ]:
models = [lr_model, rf_model, xgb_model]

In [ ]:
def model_metric(models,X_train, X_test, y_train, y_test):

  cols = ['Train accuracy', 'Test accuracy', 'Train precision', 'Test precision', 'Train recall', 'Test recall',
          'Train f1 score', 'Test f1 score', 'Train ROC-AUC', 'Test ROC-AUC']
  model_df = pd.Dataframe(columns=cols)
  conf_train, conf_test = {}, {}

  i = 0
  for model in models:

    model.fit(X_train, y_train)
    y_pred_train = model.predict(X_train)
    y_pred_test = model.predict(X_test)

    model_df.loc[i,'Train accuracy'] = accuracy_score(y_train, y_pred_train).round(2)
    model_df.loc[i,'Test accuracy'] = accuracy_score( y_test, y_pred_test).round(2)
    model_df.loc[i,'Train precision'] = precision_score(y_train, y_pred_train).round(2)
    model_df.loc[i,'Test precision'] = precision_score( y_test, y_pred_test).round(2)
    model_df.loc[i,'Train recall'] = recall_score(y_train, y_pred_train).round(2)
    model_df.loc[i,'Test recall'] = recall_score(y_test, y_pred_test).round(2)
    model_df.loc[i,'Train f1 score'] = f1_score(y_train, y_pred_train).round(2)
    model_df.loc[i,'Test f1 score'] = f1_score(y_test, y_pred_test).round(2)
    model_df.loc[i,'Train ROC-AUC'] = roc_auc__score(y_train, y_pred_train).round(2)
    model_df.loc[i,'Test ROC-AUC'] = roc_auc_score( y_test, y_pred_test).round(2)

    conf_train[model.__class__.__name__] = confusion_matrix(y_train, y_pred_train)
    conf_test[model.__class__.__name__] = confusion_matrix(y_test, y_pred_test)

In [ ]:
model_df, conf_train, conf_test = model_metric(models,X_train,y_train,X_test,y_test)

In [ ]:
model_df

Train accuracy Test accuracy  ... Test ROC-AUC              Model Name
0           0.75          0.75  ...         0.71      LogisticRegression
1           0.81          0.81  ...         0.75  RandomForestClassifier
2           0.86          0.83  ...         0.81           XGBClassifier

[3 rows x 11 columns]

In [ ]:
# Import KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

#Setup arrays to store training and test accuracies
neighbors = np.arange(1,9)
train_accuracy =np.empty(len(neighbors))
test_accuracy = np.empty(len(neighbors))

for i,k in enumerate(neighbors):
    # Setup a knn classifier with k neighbors
    knn = KNeighborsClassifier(n_neighbors=k)

    # Fit the model
    knn.fit(X_train, y_train)

    # Compute accuracy on the training set
    train_accuracy[i] = knn.score(X_train, y_train)

    # Compute accuracy on the test set
    test_accuracy[i] = knn.score(X_test, y_test)

In [ ]:
# In case of classifier like knn the parameter to be tuned is n_neighbors
param_grid = {'n_neighbors':np.arange(1,50)}

In [ ]:
knn = KNeighborsClassifier()
knn_cv= GridSearchCV(knn,param_grid,cv=5)
knn_cv.fit(X,y)
knn_cv.best_params_

In [ ]:
#naive bayes classifier.

In [ ]:
from sklearn.model_selection import train_test_split
msg_train,msg_test,label_train,label_test = train_test_split(message['tokenized_message'],message['label'],test_size=0.2)

In [ ]:
train_array= train_vectorized.toarray()
test_array = test_vectorized.toarray()

In [ ]:
from sklearn.naive_bayes import GaussianNB
spam_detect_model = GaussianNB().fit(train_array,label_train)

In [ ]:
train_preds = spam_detect_model.predict(train_array)
test_preds = spam_detect_model.predict(test_array)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
# Confusion matrices for train and test

print(confusion_matrix(label_train,train_preds))
print(confusion_matrix(label_test,test_preds))

[[2958  911]
 [   0  588]]
[[724 232]
 [ 11 148]]


In [ ]:
# Print the classification report for train and test
print(classification_report(label_train,train_preds))
print("\n")
print(classification_report(label_test,test_preds))

              precision    recall  f1-score   support

         ham       1.00      0.76      0.87      3869
        spam       0.39      1.00      0.56       588

    accuracy                           0.80      4457
   macro avg       0.70      0.88      0.72      4457
weighted avg       0.92      0.80      0.83      4457



              precision    recall  f1-score   support

         ham       0.99      0.76      0.86       956
        spam       0.39      0.93      0.55       159

    accuracy                           0.78      1115
   macro avg       0.69      0.84      0.70      1115
weighted avg       0.90      0.78      0.81      1115



In [ ]:
from sklearn.naive_bayes import GaussianNB
spam_detect_model = GaussianNB().fit(train_array,label_train)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(train_array,label_train)

In [ ]:
`````````` from sklearn.naive_bayes import BernoulliNB
spam_detect_model = BernoulliNB().fit(train_array,label_train)

In [ ]:
from sklearn import svm
clf = svm.SVC()


In [ ]:
 clf.fit(train_vectorized, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
test_pred=clf.predict(test_vectorized)

In [ ]:
# Confusion matrices for train and test

print(confusion_matrix(y_train,train_pred))
print(confusion_matrix(y_test,test_pred))

[[5483   23]
 [ 166 1252]]
[[3585   87]
 [ 376  569]]


In [ ]:
from sklearn.model_selection import GridSearchCV


In [ ]:
param_dict = {'C': [0.1, 1, 10, 1000],
              'gamma': [1, 0.1, 0.01, 0.0001],
              'kernel': ['rbf','linear','poly']}

In [ ]:
grid = GridSearchCV(clf, param_dict,n_jobs=2, cv=5, verbose = 10,scoring='accuracy')


In [ ]:
grid.fit(train_vectorized,y_train)

In [ ]:
grid.best_params_

{'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}

In [ ]:
g_pred_tr=grid.predict(train_vectorized)

In [ ]:
g_pred_test=grid.predict(test_vectorized)

In [ ]:
# Confusion matrices for train and test

print(confusion_matrix(y_train,g_pred_tr))
print(confusion_matrix(y_test,g_pred_test))

[[5467   39]
 [ 117 1301]]
[[3531  141]
 [ 266  679]]


In [ ]:
# Check Unique Values for each variable.
for i in dataset.columns.tolist():
  print("No. of unique values in ",i,"is",dataset[i].nunique(),".")

In [ ]:
f = open("/content/drive/MyDrive/demofile1.txt", "a")
f.write("this is also")
f.close()

#open and read the file after the appending:
f = open("/content/drive/MyDrive/demofile1.txt", "r")
print(f.read())

Now the file has more content!this is also


In [ ]:
n=2
print(f"{n} is the thing")

2 is the thing


### K S Chart

In [ ]:
def ks(data=None,target=None, prob=None):
    data['target0'] = 1 - data[target]
    data['bucket'] = pd.qcut(data[prob], 10)
    grouped = data.groupby('bucket', as_index = False)
    kstable = pd.DataFrame()
    kstable['min_prob'] = grouped.min()[prob]
    kstable['max_prob'] = grouped.max()[prob]
    kstable['events']   = grouped.sum()[target]
    kstable['nonevents'] = grouped.sum()['target0']
    kstable = kstable.sort_values(by="min_prob", ascending=False).reset_index(drop = True)
    kstable['event_rate'] = (kstable.events / data[target].sum()).apply('{0:.2%}'.format)
    kstable['nonevent_rate'] = (kstable.nonevents / data['target0'].sum()).apply('{0:.2%}'.format)
    kstable['cum_eventrate']=(kstable.events / data[target].sum()).cumsum()
    kstable['cum_noneventrate']=(kstable.nonevents / data['target0'].sum()).cumsum()
    kstable['KS'] = np.round(kstable['cum_eventrate']-kstable['cum_noneventrate'], 3) * 100

    #Formating
    kstable['cum_eventrate']= kstable['cum_eventrate'].apply('{0:.2%}'.format)
    kstable['cum_noneventrate']= kstable['cum_noneventrate'].apply('{0:.2%}'.format)
    kstable.index = range(1,11)
    kstable.index.rename('Decile', inplace=True)
    pd.set_option('display.max_columns', 9)
    print(kstable)

    #Display KS
    from colorama import Fore
    print(Fore.RED + "KS is " + str(max(kstable['KS']))+"%"+ " at decile " + str((kstable.index[kstable['KS']==max(kstable['KS'])][0])))
    return(kstable)

In [ ]:
mydf = ks(data=df,target="y", prob="p")